name: iOS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Show Available Simulators
        run: xcrun simctl list devices

      - name: Build App
        run: |
          xcodebuild clean build \
          -project WeatherApp/WeatherApp.xcodeproj \
          -scheme WeatherApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.6' \
          CODE_SIGNING_ALLOWED=NO

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project WeatherApp/WeatherApp.xcodeproj \
          -scheme WeatherApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.6' \
          CODE_SIGNING_ALLOWED=NO
