```yaml
name: iOS CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Folder Structure
        run: ls -R

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build App
        run: |
          xcodebuild clean build \
          -project WeatherApp/WeatherApp.xcodeproj \
          -scheme WeatherApp \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGNING_ALLOWED=NO

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project WeatherApp/WeatherApp.xcodeproj \
          -scheme WeatherApp \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          CODE_SIGNING_ALLOWED=NO
```
